### ISSUE TITLE
Kyma CR watcher

### ISSUE THREAD

**Issue by strekm** [kyma-project/eventing-auth-manager#13]
**Description**

Enhance eventing auth controller with a watch over Kyma CR. Eventing auth controller should react on Kyma CR creation / deletion and create / delete EventingAuth CR accordingly. For existing Kyma CR EventingAuth CR should be created. Consider that on initial run there might be 500+ Kyma CRs. 

DoD:
- [x] EventingAuth CR created on Kyma CR creation
- [x] EventingAuth CR deleted on Kyma CR deletion
- [x] EventingAuth CR created for existing Kyma CRs
- [x] controller docu updated

**Attachments**
part of: https://github.com/kyma-project/eventing-auth-manager/issues/1

**Comment by k15r** [comment]
looks good, thx
