### ISSUE TITLE
Setup Release process for EAM

### ISSUE THREAD

**Issue by k15r** [kyma-project/eventing-auth-manager#149]
## Description

Setup a release process to release new versions of EAM and deploy them to the various landscapes.

## Acceptance

- [x] setup a release process for new EAM versions similar to [KEB](https://github.com/kyma-project/kyma-environment-broker/blob/main/.github/workflows/create-release.yaml), [doc](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/04-20-release.md)
  - releases follow semantic versioning
  - APP_VERSION in helm charts needs to match the released version 
- [x] release a new version of EAM based on the new release process
- [x] deploy the new version to dev, stage and prod.
  - [x] dev
  - [x] stage
  - [x] prod

**Comment by mfaizanse** [comment]
### Checklist
- [ ] enable `Validate labels` step.

**Comment by mfaizanse** [comment]
![image](https://github.com/kyma-project/eventing-auth-manager/assets/9897945/3b93dcc6-f052-4d4e-aa4f-2cb4ef981520)
